openapi: 3.1.0
info:
  title: Wish site OpenAPI spec
  version: 0.0.2
servers:
  - url: http://localhost:8080/api/
    description: Dev Server
tags:
  - name: Users
    description: Управление пользователями
  - name: Wishes
    description: Управление желаниями

paths:
  # --- USERS ---
  /users:
    get:
      summary: Метод получения всех юзеров
      tags:
        - Users
      operationId: getAllUsers
      responses:
        '200':
          description: Успешный ответ со списком всех юзеров
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserResponse"
        '400':
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      summary: Метод создания юзера
      tags:
        - Users
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRequest"
      responses:
        '200':
          description: Успешный ответ с созданным юзером
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        '400':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users/{user_id}:
    parameters:
      - name: user_id
        in: path
        required: true
        description: Идентификатор юзера
        schema:
          type: integer
          format: int64
    get:
      summary: Метод получения конкретного user по id
      tags:
        - Users
      operationId: getUserById
      responses:
        '200':
          description: Успешный ответ с конкретным юзером
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        '404':
          description: Юзер не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      summary: Метод удаления юзера по id
      tags:
        - Users
      operationId: deleteUserById
      responses:
        '200':
          description: "Успешный ответ: юзер с user_id удален"
        '404':
          description: Юзер не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    patch:
      summary: Обновление данных юзера по id
      tags:
        - Users
      operationId: updateUserById
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdateRequest"
      responses:
        '200':
          description: Успешный ответ с обновленным юзером
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        '400':
          description: Ошибка валидации

  # --- WISHES ---


  /users/{user_id}/wishes:
    parameters:
      - name: user_id
        in: path
        required: true
        description: ID владельца желаний
        schema:
          type: integer
          format: int64

    get:
      summary: Получить все желания конкретного пользователя
      tags:
        - Wishes
      operationId: getUserWishes
      responses:
        '200':
          description: Список желаний пользователя
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WishResponse"

    post:
      summary: Создать новое желание для пользователя
      tags:
        - Wishes
      operationId: createWish
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WishRequest"
      responses:
        '200':
          description: Желание успешно создано
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WishResponse"

  /wishes/{wish_id}:
    parameters:
      - name: wish_id
        in: path
        required: true
        description: ID желания
        schema:
          type: integer
          format: int64

    get:
      summary: Получить детали конкретного желания
      tags:
        - Wishes
      operationId: getWishById
      responses:
        '200':
          description: Детали желания
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WishResponse"
        '404':
          description: Желание не найдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      summary: Удалить желание
      tags:
        - Wishes
      operationId: deleteWishById
      responses:
        '200':
          description: Желание удалено
        '404':
          description: Желание не найдено

    patch:
      summary: Обновить желание
      tags:
        - Wishes
      operationId: updateWishById
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WishUpdateRequest"
      responses:
        '200':
          description: Желание обновлено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WishResponse"

components:
  schemas:
    # --- USER MODELS ---
    UserResponse:
      type: object
      required:
        - user_id
        - name
        - role
        - created_at
      properties:
        user_id:
          type: integer
          format: int64
          example: 1337
        name:
          type: string
          example: Artem Dabstep
        role:
          type: string
          description: "Роль юзера: Админ или обычный"
          enum:
            - admin
            - member
        created_at:
          type: string
          format: date-time
          example: "2025-11-27T16:44:00+03:00"

    UserRequest:
      type: object
      required:
        - name
        - password
      properties:
        name:
          type: string
          example: Artem Dabstep
        password:
          type: string
          format: password
          example: "SuperSecret"

    UserUpdateRequest:
      type: object
      properties:
        name:
          type: string
          example: New Name 123
          description: Новое имя (опционально)
        role:
          type: string
          enum:
            - admin
            - member
          default: member
          description: Новая роль (опционально)
        password:
          type: string
          format: password
          description: Новый пароль (опционально)

    # --- WISH MODELS ---
    WishResponse:
      type: object
      required:
        - wish_id
        - title
        - created_at
        - owner_id
      properties:
        wish_id:
          type: integer
          format: int64
          example: 101
        owner_id:
          type: integer
          format: int64
          description: ID пользователя, создавшего желание
          example: 1337
        title:
          type: string
          description: Название желания
          example: "PlayStation 5"
        description:
          type: string
          description: Подробное описание
          example: "С дисководом, желательно белую"
        photo_url:
          type: string
          description: Ссылка на фото (из MinIO)
          example: "https://minio.dabwish.com/images/ps5.jpg"
        price:
          type: number
          format: double
          description: Ориентировочная цена
          example: 499.99
        created_at:
          type: string
          format: date-time
          example: "2025-12-01T10:00:00+03:00"

    WishRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          example: "PlayStation 5"
        description:
          type: string
          example: "С дисководом"
        photo_url:
          type: string
          description: Ссылка на уже загруженное фото
        price:
          type: number
          format: double

    WishUpdateRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        photo_url:
          type: string
        price:
          type: number
          format: double

    # --- COMMON ---
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: Resource not found