spring:
  application:
    name: dabwish
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dev-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:dev}

server:
  port: ${MY_PORT:8080}
logging:
  level:
    root: WARN
    liquibase: INFO
    org.springframework.boot.autoconfigure.liquibase: INFO