spring:
  application:
    name: dabwish
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dev-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:dev}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
      specific.avro.reader: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        auto.register.schemas: true


server:
  port: ${MY_PORT:8080}
logging:
  level:
    root: WARN
    liquibase: INFO
    org.springframework.boot.autoconfigure.liquibase: INFO

app:
  kafka:
    enabled: true
    topics:
      user-created: ${USER-CREATED-KAFKA:user-created-events}
      wish-created: ${WISH-CREATED-KAFKA:wish-created-events}
      wish-updated: ${WISH-UPDATED-KAFKA:wish-updated-events}