spring:
  application:
    name: dabwish
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dabwish}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  cache:
    type: redis
    # type: none #for Hikari
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 5000
      lettuce:
        pool:
          enabled: true
          max-active: 32
          max-idle: 16
          min-idle: 4
          max-wait: 100ms
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:dev}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
      specific.avro.reader: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        auto.register.schemas: true


server:
  port: ${MY_PORT:8080}
logging:
  level:
    root: WARN
    liquibase: INFO
    org.springframework.boot.autoconfigure.liquibase: INFO

app:
  kafka:
    enabled: true
    topics:
      user-created: ${USER-CREATED-KAFKA:user-created-events}
      wish-created: ${WISH-CREATED-KAFKA:wish-created-events}
      wish-updated: ${WISH-UPDATED-KAFKA:wish-updated-events}
  jwt:
    secret: ${APP_JWT_SECRET:Xtd5Fk7WIZS4tpwRMaqqTlaJBVkRpr3U}
    expiration-seconds: ${APP_JWT_EXPIRATION:3600}
  cache:
    logging:
      enabled: ${APP_LOGGING:true}
    ttl:
      users-seconds: ${APP_CACHE_USERS_TTL:900}
      wishes-seconds: ${APP_CACHE_WISHES_TTL:600}
      wish-list-seconds: ${APP_CACHE_WISH_LIST_TTL:120}

management:
  endpoints:
    web:
      exposure:
        include: "metrics,prometheus"
  metrics:
    cache:
      instrument: true
    tags:
      application: dabwish
    enable:
      cache: true

minio:
  url: http://localhost:9000
  access-key: ${MINIO_ROOT_USER:minioadmin}
  secret-key: ${MINIO_ROOT_PASSWORD:minioadmin}
  bucket-name: dabwish-images

